services:
  - type: web
    name: django-web
    env: docker
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: django-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: django-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: django-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: django-db
          property: password
      - key: DEBUG
        value: "False"
databases:
  - name: django-db
    plan: free
