# Generated by Django 3.2.25 on 2025-04-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250421_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='num_pages',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='thumbnail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
