# Generated by Django 4.2.19 on 2025-04-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250422_1035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booklist',
            old_name='category',
            new_name='status',
        ),
    ]
