# Generated by Django 4.2.19 on 2025-04-28 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='favourites',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booklist',
            name='pages_read',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='status',
            field=models.CharField(choices=[('read_later', 'Read later'), ('currently_reading', 'Currently reading'), ('finished', 'Finished'), ('on_hold', 'On hold'), ('re_reading', 'Re-reading'), ('dropped_reading', 'Dropped reading')], max_length=20),
        ),
    ]
