# Generated by Django 4.2.19 on 2025-04-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_booklist_favourites_booklist_pages_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='pages_read',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
